apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-service-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration-service
  template:
    metadata:
      labels:
        app: expiration-service
    spec:
      containers:
        - name: expiration-service
          image: jamesjasenia/expiration-service
          env:
            - name: NATS_URL
              value: 'http://nats-streaming-clusterip-srv:4222'
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: REDIS_HOST
              value: expiration-service-redis-clusterip-srv
