apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-streaming-depl
  labels:
    app: nats-streaming-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats-streaming-depl
  template:
    metadata:
      labels:
        app: nats-streaming-depl
    spec:
      containers:
        - name: nats-streaming
          image: nats-streaming:0.17.0
          args: [
              '-p',     # Port for the NATS server (listening for client connections)
              '4222',
              '-m',
              '8222',
              '-hbi',   # Heartbeat Interval: time between heartbeat pings to clients
              '5s',
              '-hbt',   # Heartbeat Timeout: time to wait for a response from a client
              '5s',
              '-hbf',    # Heartbeat Failures: number of failed heartbeats before considering a client disconnected
              '2',
              '-SD',
              '-cid',
              'ticketing',
            ]
---
apiVersion: v1
kind: Service
metadata:
  name: nats-streaming-clusterip-srv
  labels:
    app: nats-streaming-clusterip-srv
spec:
  selector:
    app: nats-streaming-depl
  ports:
    - name: client
      protocol: TCP
      port: 4222
      targetPort: 4222
    - name: monitoring
      protocol: TCP 
      port: 8222
      targetPort: 8222
  