apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-service-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-service
  template:
    metadata:
      labels:
        app: orders-service
    spec:
      containers:
        - name: orders-service
          image: jamesjasenia/orders-service
          env:
            - name: NATS_URL
              value: 'http://nats-streaming-clusterip-srv:4222'
            - name: NATS_CLUSTER_ID
              value: orders
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MONGO_URI
              value: mongodb://orders-service-mongo-clusterip-srv:27017/orders
            - name: JWT_KEY
              valueFrom: 
                secretKeyRef: 
                  name: jwt-secret
                  key: JWT_KEY

---
apiVersion: v1
kind: Service
metadata:
  name: orders-service-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: orders-service
  ports:
  - name: orders-service
    protocol: TCP
    port: 3000
    targetPort: 3000
