apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-service-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-service
  template:
    metadata:
      labels:
        app: payments-service
    spec:
      containers:
        - name: payments-service
          image: jamesjasenia/payments-service
          env:
            - name: NATS_URL
              value: 'http://nats-streaming-clusterip-srv:4222'
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MONGO_URI
              value: mongodb://payments-service-mongo-clusterip-srv:27017/payments
            - name: JWT_KEY
              valueFrom: 
                secretKeyRef: 
                  name: jwt-secret
                  key: JWT_KEY
            - name: STRIPE_KEY
              valueFrom: 
                secretKeyRef: 
                  name: stripe-secret
                  key: STRIPE_KEY

---
apiVersion: v1
kind: Service
metadata:
  name: payments-service-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: payments-service
  ports:
  - name: payments-service
    protocol: TCP
    port: 3000
    targetPort: 3000
