apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-service-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket-service
  template:
    metadata:
      labels:
        app: ticket-service
    spec:
      containers:
        - name: ticket-service
          image: jamesjasenia/ticket-service
          env:
            - name: MONGO_URI
              value: mongodb://ticket-service-mongo-clusterip-srv:27017/ticket
            - name: JWT_KEY
              valueFrom: 
                secretKeyRef: 
                  name: jwt-secret
                  key: JWT_KEY

---
apiVersion: v1
kind: Service
metadata:
  name: ticket-service-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: ticket-service
  ports:
  - name: ticket-service
    protocol: TCP
    port: 3000
    targetPort: 3000
